export type TestPriority = "P0" | "P1";
export type TestKind = "happy" | "edge" | "error";
export type TestScope = "core" | "wireframe-extension";

export type SrsTestCase = {
  id: string;
  route: string;
  feature: string;
  title: string;
  priority: TestPriority;
  kind: TestKind;
  scope: TestScope;
  source: readonly string[];
  mocks: readonly string[];
  selectors: readonly string[];
  expected: string;
};

export const srsTestCases: readonly SrsTestCase[] = [
  { id: "NAV-01", route: "/calendar", feature: "navigation", title: "redirect unauthenticated users to /auth", priority: "P0", kind: "error", scope: "core", source: ["BR-2", "BR-3", "BR-34"], mocks: [], selectors: ["auth-page", "auth-login-form"], expected: "Protected routes redirect to /auth and hide private content." },
  { id: "NAV-02", route: "/calendar", feature: "navigation", title: "navigate between authenticated sections from the app shell", priority: "P0", kind: "happy", scope: "core", source: ["Wireframe: calendar-dashboard"], mocks: ["GET /appointments", "GET /notifications"], selectors: ["app-sidebar", "nav-calendar", "nav-appointments", "nav-tags", "nav-profile"], expected: "Sidebar navigation changes routes and shows the destination heading." },

  { id: "AUTH-01", route: "/auth", feature: "authentication", title: "register a new account", priority: "P0", kind: "happy", scope: "core", source: ["UC-1", "BR-1", "BR-32"], mocks: ["POST /auth/register"], selectors: ["auth-tab-register", "register-name-input", "register-email-input", "register-password-input", "register-confirm-password-input", "register-submit", "register-success-banner"], expected: "Registration succeeds and shows a verification-required banner." },
  { id: "AUTH-02", route: "/auth", feature: "authentication", title: "show duplicate-email registration error", priority: "P0", kind: "error", scope: "core", source: ["UC-1 E1", "BR-1"], mocks: ["POST /auth/register"], selectors: ["register-email-input", "register-submit", "register-email-error"], expected: "The form stays open and shows email already registered." },
  { id: "AUTH-03", route: "/auth", feature: "authentication", title: "validate password confirmation before register submit", priority: "P0", kind: "edge", scope: "core", source: ["UC-1 E2"], mocks: [], selectors: ["register-password-input", "register-confirm-password-input", "register-confirm-error"], expected: "No request is sent and a mismatch error is shown." },
  { id: "AUTH-04", route: "/auth", feature: "authentication", title: "log in and redirect to /calendar", priority: "P0", kind: "happy", scope: "core", source: ["UC-2", "BR-2", "BR-3"], mocks: ["POST /auth/login", "GET /appointments", "GET /notifications"], selectors: ["login-email-input", "login-password-input", "login-submit", "calendar-page"], expected: "Successful login redirects the user to the calendar dashboard." },
  { id: "AUTH-05", route: "/auth", feature: "authentication", title: "show invalid-credentials error", priority: "P0", kind: "error", scope: "core", source: ["UC-2 E1"], mocks: ["POST /auth/login"], selectors: ["login-submit", "login-error-banner"], expected: "The user remains on /auth and sees a login failed message." },
  { id: "AUTH-06", route: "/forgot-password", feature: "authentication", title: "request a password reset link", priority: "P0", kind: "happy", scope: "core", source: ["UC-4"], mocks: ["POST /auth/forgot-password"], selectors: ["forgot-password-email-input", "forgot-password-submit", "forgot-password-success"], expected: "The page confirms the reset email was sent." },
  { id: "AUTH-07", route: "/forgot-password", feature: "authentication", title: "show unknown-email forgot-password error", priority: "P0", kind: "error", scope: "core", source: ["UC-4 E1"], mocks: ["POST /auth/forgot-password"], selectors: ["forgot-password-submit", "forgot-password-error"], expected: "The user sees email not registered feedback." },
  { id: "AUTH-08", route: "/reset-password?token=expired-token", feature: "authentication", title: "reject an invalid or expired reset token", priority: "P0", kind: "error", scope: "core", source: ["UC-4 E2"], mocks: ["POST /auth/reset-password"], selectors: ["reset-password-submit", "reset-password-error"], expected: "The form shows invalid or expired token feedback and asks for a new link." },

  { id: "CAL-01", route: "/calendar", feature: "calendar", title: "switch between Day, Week, Month, and Agenda", priority: "P0", kind: "happy", scope: "core", source: ["UC-9", "UC-10", "BR-13"], mocks: ["GET /appointments"], selectors: ["calendar-view-day", "calendar-view-week", "calendar-view-month", "calendar-view-agenda"], expected: "Each calendar mode renders and Agenda shows a chronological list." },
  { id: "CAL-02", route: "/calendar", feature: "calendar", title: "navigate previous and next periods", priority: "P0", kind: "happy", scope: "core", source: ["UC-9"], mocks: ["GET /appointments"], selectors: ["calendar-period-label", "calendar-nav-prev", "calendar-nav-next"], expected: "The period label changes and appointment data reloads." },
  { id: "CAL-03", route: "/calendar", feature: "calendar", title: "open the create flow from an empty slot or date cell", priority: "P0", kind: "happy", scope: "core", source: ["UC-6", "Wireframe: calendar-dashboard"], mocks: ["GET /appointments"], selectors: ["calendar-day-cell", "calendar-slot", "appointment-form-modal", "appointment-start-input"], expected: "The appointment form opens with the selected date or time prefilled." },

  { id: "APPT-01", route: "/appointments", feature: "appointments", title: "create a new appointment", priority: "P0", kind: "happy", scope: "core", source: ["UC-6", "BR-6", "BR-7", "BR-8"], mocks: ["GET /appointments", "POST /appointments"], selectors: ["appointment-create-trigger", "appointment-title-input", "appointment-start-input", "appointment-end-input", "appointment-save", "appointment-row"], expected: "A valid appointment is created and rendered in the list." },
  { id: "APPT-02", route: "/appointments", feature: "appointments", title: "block invalid time ranges", priority: "P0", kind: "error", scope: "core", source: ["UC-6 E1", "BR-6"], mocks: [], selectors: ["appointment-start-input", "appointment-end-input", "appointment-time-error"], expected: "Submitting start-after-end is blocked with inline validation." },
  { id: "APPT-03", route: "/appointments", feature: "appointments", title: "block appointments in the past", priority: "P0", kind: "error", scope: "core", source: ["UC-6 E1", "BR-7"], mocks: [], selectors: ["appointment-start-input", "appointment-time-error"], expected: "Past appointments cannot be submitted." },
  { id: "APPT-04", route: "/appointments", feature: "appointments", title: "show conflict feedback for overlaps", priority: "P0", kind: "error", scope: "core", source: ["UC-6 E2", "BR-8"], mocks: ["GET /appointments", "POST /appointments"], selectors: ["appointment-save", "appointment-conflict-alert"], expected: "Overlapping appointments return conflict feedback without closing the form." },
  { id: "APPT-05", route: "/appointments", feature: "appointments", title: "update a single appointment", priority: "P0", kind: "happy", scope: "core", source: ["UC-7"], mocks: ["GET /appointments", "PUT /appointments/:id"], selectors: ["appointment-edit-trigger", "appointment-form-modal", "appointment-save"], expected: "Editing a single appointment persists changes and refreshes the UI." },
  { id: "APPT-06", route: "/appointments", feature: "appointments", title: "prompt for recurrence scope on recurring update", priority: "P0", kind: "edge", scope: "core", source: ["UC-7 A1", "BR-12"], mocks: ["GET /appointments", "PUT /appointments/:id"], selectors: ["appointment-edit-trigger", "recurrence-scope-dialog", "recurrence-scope-single", "recurrence-scope-series"], expected: "Recurring edits ask for single-instance vs entire-series scope." },
  { id: "APPT-07", route: "/appointments", feature: "appointments", title: "prompt for recurrence scope on recurring delete", priority: "P0", kind: "edge", scope: "core", source: ["UC-8 A1", "BR-12"], mocks: ["GET /appointments", "DELETE /appointments/:id"], selectors: ["appointment-delete-trigger", "appointment-delete-dialog", "delete-scope-single", "delete-scope-series", "delete-confirm"], expected: "Recurring deletes ask for single-instance vs entire-series scope." },
  { id: "APPT-08", route: "/appointments", feature: "appointments", title: "toggle appointment status between scheduled and completed", priority: "P0", kind: "happy", scope: "core", source: ["UC-12"], mocks: ["GET /appointments", "PATCH /appointments/:id/status"], selectors: ["appointment-status-trigger", "appointment-status-badge"], expected: "Status changes update the badge and row styling." },
  { id: "APPT-09", route: "/appointments", feature: "appointments", title: "search by keyword", priority: "P0", kind: "happy", scope: "core", source: ["UC-13", "BR-27"], mocks: ["GET /appointments"], selectors: ["appointment-search-input", "appointment-row"], expected: "Searching filters the result set by title and description." },
  { id: "APPT-10", route: "/appointments", feature: "appointments", title: "filter by tag, status, and date range", priority: "P0", kind: "happy", scope: "core", source: ["UC-13", "BR-27"], mocks: ["GET /appointments", "GET /tags"], selectors: ["filter-tag", "filter-status", "filter-date-from", "filter-date-to", "appointment-row"], expected: "Filtering updates the request and the rendered appointments." },
  { id: "APPT-11", route: "/appointments", feature: "appointments", title: "show a no-results empty state", priority: "P0", kind: "edge", scope: "core", source: ["UC-13 E1"], mocks: ["GET /appointments"], selectors: ["appointment-empty-state", "appointment-clear-filters"], expected: "No matching appointments render a recoverable empty state." },
  { id: "APPT-12", route: "/appointments", feature: "appointments", title: "preserve form state on unexpected save failure", priority: "P0", kind: "error", scope: "core", source: ["UI-2", "ROB-2"], mocks: ["POST /appointments"], selectors: ["appointment-form-modal", "appointment-error-banner", "appointment-title-input"], expected: "Server failures keep the form open, preserve input, and show an actionable error." },

  { id: "RECUR-01", route: "/appointments", feature: "recurrence", title: "create a recurring appointment", priority: "P0", kind: "happy", scope: "core", source: ["UC-11", "BR-9", "BR-10"], mocks: ["POST /appointments"], selectors: ["appointment-recurrence-toggle", "appointment-recurrence-pattern", "appointment-recurrence-end", "appointment-save"], expected: "A valid recurrence rule is saved with the appointment." },
  { id: "RECUR-02", route: "/appointments", feature: "recurrence", title: "reject invalid recurrence rules", priority: "P0", kind: "error", scope: "core", source: ["UC-11 E1", "BR-9"], mocks: [], selectors: ["appointment-recurrence-toggle", "appointment-recurrence-error"], expected: "Invalid recurrence rules are blocked before submission." },

  { id: "TAG-01", route: "/tags", feature: "tags", title: "create a tag with color preview", priority: "P0", kind: "happy", scope: "core", source: ["UC-14", "BR-19", "BR-20"], mocks: ["GET /tags", "POST /tags"], selectors: ["tag-create-trigger", "tag-name-input", "tag-color-input", "tag-preview", "tag-save"], expected: "A new tag is created and previewed before saving." },
  { id: "TAG-02", route: "/tags", feature: "tags", title: "reject duplicate tag names", priority: "P0", kind: "error", scope: "core", source: ["UC-14 E1"], mocks: ["GET /tags", "POST /tags"], selectors: ["tag-name-input", "tag-save", "tag-name-error"], expected: "Duplicate names are rejected with inline feedback." },
  { id: "TAG-03", route: "/tags", feature: "tags", title: "rename a tag and propagate it to appointments", priority: "P0", kind: "happy", scope: "core", source: ["UC-14"], mocks: ["GET /tags", "PUT /tags/:id", "GET /appointments"], selectors: ["tag-rename-trigger", "tag-rename-input", "tag-rename-save"], expected: "Renamed tags update both the tag list and appointment labels." },
  { id: "TAG-04", route: "/tags", feature: "tags", title: "delete a tag after confirmation", priority: "P0", kind: "happy", scope: "core", source: ["UC-14"], mocks: ["GET /tags", "DELETE /tags/:id", "GET /appointments"], selectors: ["tag-delete-trigger", "tag-delete-dialog", "tag-delete-confirm"], expected: "Deleting a tag removes it from the table and linked appointments." },

  { id: "REM-01", route: "/appointments", feature: "reminders", title: "save multiple reminders for one appointment", priority: "P0", kind: "happy", scope: "core", source: ["UC-15", "UC-15 A1", "BR-21", "BR-22"], mocks: ["POST /appointments/:id/reminders"], selectors: ["appointment-reminders-trigger", "reminder-add", "reminder-row", "reminder-save"], expected: "Multiple reminders are saved for a single appointment." },
  { id: "REM-02", route: "/appointments", feature: "reminders", title: "reject reminder times after the appointment start", priority: "P0", kind: "error", scope: "core", source: ["UC-15 E1", "BR-21"], mocks: [], selectors: ["reminder-custom-value", "reminder-save", "reminder-error"], expected: "Invalid reminder timing is blocked with clear validation." },
  { id: "REM-03", route: "/calendar", feature: "reminders", title: "show a real-time reminder popup and unread badge update", priority: "P0", kind: "happy", scope: "core", source: ["UC-20", "BR-23", "BR-25"], mocks: ["GET /notifications"], selectors: ["notification-popup", "notification-bell-badge"], expected: "Due reminders appear as popups and increment the unread count." },
  { id: "REM-04", route: "/notifications", feature: "reminders", title: "snooze a reminder", priority: "P0", kind: "happy", scope: "core", source: ["UC-16", "BR-24"], mocks: ["GET /notifications", "POST /reminders/:id/snooze"], selectors: ["notification-popup-snooze", "notification-log-row", "notification-status"], expected: "Snoozing hides the popup and updates the reminder status in the log." },

  { id: "NOTIF-01", route: "/notifications", feature: "notifications", title: "filter notifications and mark all as read", priority: "P1", kind: "happy", scope: "wireframe-extension", source: ["UC-17", "BR-25", "BR-26"], mocks: ["GET /notifications", "PATCH /notifications/mark-all-read"], selectors: ["notification-filter", "notification-mark-all-read", "notification-bell-badge"], expected: "Unread filtering works and mark-all-read clears the badge count." },
  { id: "NOTIF-02", route: "/notifications", feature: "notifications", title: "clear the notification log", priority: "P1", kind: "edge", scope: "wireframe-extension", source: ["UC-17", "Wireframe: notification-log"], mocks: ["GET /notifications", "DELETE /notifications"], selectors: ["notification-clear-all", "notification-empty-state"], expected: "Clearing the log renders an empty state." },

  { id: "STAT-01", route: "/statistics", feature: "statistics", title: "render weekly statistics and charts", priority: "P0", kind: "happy", scope: "core", source: ["UC-18", "BR-15", "BR-17", "BR-18", "BR-34"], mocks: ["GET /statistics"], selectors: ["statistics-period-filter", "statistics-total-card", "statistics-completed-card", "statistics-completion-rate-card"], expected: "The dashboard renders summary metrics, charts, and time-slot rankings." },
  { id: "STAT-02", route: "/statistics", feature: "statistics", title: "change the statistics period", priority: "P0", kind: "happy", scope: "core", source: ["UC-18", "BR-16"], mocks: ["GET /statistics"], selectors: ["statistics-period-filter", "statistics-period-label"], expected: "Changing the period updates the date range and metrics." },
  { id: "STAT-03", route: "/statistics", feature: "statistics", title: "show the insufficient-data empty state", priority: "P0", kind: "edge", scope: "core", source: ["UC-18 E1"], mocks: ["GET /statistics"], selectors: ["statistics-empty-state"], expected: "Low-data scenarios show an encouraging empty state instead of broken charts." },

  { id: "EXP-01", route: "/export", feature: "export", title: "preview filtered rows and download CSV", priority: "P0", kind: "happy", scope: "core", source: ["UC-19", "BR-28", "BR-29"], mocks: ["GET /appointments/export", "GET /tags"], selectors: ["export-date-from", "export-date-to", "export-tag-filter", "export-status-filter", "export-preview-table", "export-submit"], expected: "The preview honors filters and the browser starts a CSV download." },
  { id: "EXP-02", route: "/export", feature: "export", title: "show no-data feedback for empty exports", priority: "P0", kind: "edge", scope: "core", source: ["Sequence: export-data"], mocks: ["GET /appointments/export"], selectors: ["export-empty-state", "export-submit"], expected: "Zero matching rows show a no-data state before export." },

  { id: "PROF-01", route: "/profile", feature: "profile", title: "update editable profile information", priority: "P0", kind: "happy", scope: "core", source: ["UC-5"], mocks: ["GET /profile", "PUT /profile"], selectors: ["profile-name-input", "profile-timezone-select", "profile-save", "profile-success-banner"], expected: "Valid profile updates show a success confirmation." },
  { id: "PROF-02", route: "/profile", feature: "profile", title: "keep email read-only", priority: "P0", kind: "edge", scope: "core", source: ["UC-5", "Wireframe: profile-page"], mocks: ["GET /profile"], selectors: ["profile-email-input"], expected: "The email field is visible but cannot be edited." },
  { id: "PROF-03", route: "/profile", feature: "profile", title: "show validation feedback for password update failure", priority: "P0", kind: "error", scope: "wireframe-extension", source: ["Wireframe: profile-page"], mocks: ["PUT /profile/password"], selectors: ["profile-current-password-input", "profile-new-password-input", "profile-confirm-password-input", "profile-password-save", "profile-password-error"], expected: "Invalid password updates keep the form open and show inline feedback." },
  { id: "PROF-04", route: "/profile", feature: "profile", title: "block account deletion until email confirmation matches", priority: "P1", kind: "error", scope: "wireframe-extension", source: ["DI-2", "Wireframe: profile-page"], mocks: ["DELETE /profile"], selectors: ["profile-delete-trigger", "profile-delete-dialog", "profile-delete-confirmation-input", "profile-delete-submit"], expected: "Delete account stays blocked until the typed email matches." },

  { id: "REMSET-01", route: "/reminders", feature: "reminder-settings", title: "save default reminder preferences", priority: "P1", kind: "happy", scope: "wireframe-extension", source: ["Wireframe: reminder-settings"], mocks: ["GET /profile", "PUT /profile"], selectors: ["reminder-default-select", "reminder-snooze-select", "reminder-preferences-save"], expected: "Default reminder and snooze preferences persist successfully." },
];

export const p0TestCases = srsTestCases.filter((testCase) => testCase.priority === "P0");
export const p1TestCases = srsTestCases.filter((testCase) => testCase.priority === "P1");
